// AI Value Chain Data - Converted from ai_value_chain.txt
const aiValueChainData = [
    {
        site_id: 1,
        site_name: "Tenke Fungurume Mine",
        country: "Democratic Republic of Congo",
        region: "Central Africa",
        category: "mineral_extraction",
        subcategory: "cobalt",
        latitude: -10.7,
        longitude: 26.1,
        production_volume: 28500,
        production_unit: "MT_annual",
        workforce_size: 15000,
        avg_wage_usd_monthly: 60,
        environmental_impact_score: 9,
        human_rights_violations: "child_labor",
        key_companies: "China Molybdenum",
        source_authors: "Crawford, RAID",
        data_year: 2023
    },
    {
        site_id: 2,
        site_name: "Kolwezi Mining District",
        country: "Democratic Republic of Congo",
        region: "Central Africa",
        category: "mineral_extraction",
        subcategory: "cobalt",
        latitude: -10.7,
        longitude: 25.5,
        production_volume: 84000,
        production_unit: "MT_annual_district",
        workforce_size: 40000,
        avg_wage_usd_monthly: 50,
        environmental_impact_score: 10,
        human_rights_violations: "child_labor_water_contamination",
        key_companies: "Glencore, Eurasian Resources",
        source_authors: "Crawford, Kara",
        data_year: 2024
    },
    {
        site_id: 3,
        site_name: "Mutanda Mine",
        country: "Democratic Republic of Congo",
        region: "Central Africa",
        category: "mineral_extraction",
        subcategory: "cobalt",
        latitude: -10.8,
        longitude: 25.6,
        production_volume: 27300,
        production_unit: "MT_annual",
        workforce_size: 8000,
        avg_wage_usd_monthly: 65,
        environmental_impact_score: 8,
        human_rights_violations: "environmental_degradation",
        key_companies: "Glencore",
        source_authors: "Crawford, RAID",
        data_year: 2018
    },
    {
        site_id: 4,
        site_name: "KOV Mine",
        country: "Democratic Republic of Congo",
        region: "Central Africa",
        category: "mineral_extraction",
        subcategory: "cobalt",
        latitude: -10.73,
        longitude: 25.47,
        production_volume: 15000,
        production_unit: "MT_annual",
        workforce_size: 5000,
        avg_wage_usd_monthly: 55,
        environmental_impact_score: 8,
        human_rights_violations: "labor_violations",
        key_companies: "COMIDE, Gécamines",
        source_authors: "Amnesty, Crawford",
        data_year: 2023
    },
    {
        site_id: 5,
        site_name: "Salar de Uyuni",
        country: "Bolivia",
        region: "South America",
        category: "mineral_extraction",
        subcategory: "lithium",
        latitude: -20.13,
        longitude: -67.49,
        production_volume: 23000000,
        production_unit: "MT_reserves",
        workforce_size: 2000,
        avg_wage_usd_monthly: 800,
        environmental_impact_score: 7,
        human_rights_violations: "indigenous_displacement",
        key_companies: "YLB, Lilac Solutions",
        source_authors: "Harvard IRR, Human Rights Pulse",
        data_year: 2024
    },
    {
        site_id: 6,
        site_name: "Salar de Atacama",
        country: "Chile",
        region: "South America",
        category: "mineral_extraction",
        subcategory: "lithium",
        latitude: -24.0,
        longitude: -69.0,
        production_volume: 180000,
        production_unit: "MT_annual",
        workforce_size: 3500,
        avg_wage_usd_monthly: 1200,
        environmental_impact_score: 8,
        human_rights_violations: "water_depletion",
        key_companies: "SQM, Albemarle",
        source_authors: "Harvard IRR",
        data_year: 2023
    },
    {
        site_id: 7,
        site_name: "Bayan Obo Mine",
        country: "China",
        region: "Asia",
        category: "mineral_extraction",
        subcategory: "rare_earth",
        latitude: 41.8,
        longitude: 109.9,
        production_volume: 45000,
        production_unit: "MT_annual",
        workforce_size: 25000,
        avg_wage_usd_monthly: 400,
        environmental_impact_score: 10,
        human_rights_violations: "radioactive_contamination",
        key_companies: "China Northern Rare Earth",
        source_authors: "Harvard IRR, IPS",
        data_year: 2024
    },
    {
        site_id: 8,
        site_name: "Myanmar Kachin State",
        country: "Myanmar",
        region: "Asia",
        category: "mineral_extraction",
        subcategory: "rare_earth",
        latitude: 25.0,
        longitude: 98.0,
        production_volume: 31000,
        production_unit: "MT_annual",
        workforce_size: 50000,
        avg_wage_usd_monthly: 150,
        environmental_impact_score: 10,
        human_rights_violations: "toxic_exposure_death",
        key_companies: "Military Junta",
        source_authors: "Global Witness",
        data_year: 2024
    },
    {
        site_id: 9,
        site_name: "Escondida Mine",
        country: "Chile",
        region: "South America",
        category: "mineral_extraction",
        subcategory: "copper",
        latitude: -24.3,
        longitude: -69.1,
        production_volume: 1350000,
        production_unit: "MT_annual",
        workforce_size: 8000,
        avg_wage_usd_monthly: 2500,
        environmental_impact_score: 6,
        human_rights_violations: "water_usage",
        key_companies: "BHP Billiton",
        source_authors: "NS Energy",
        data_year: 2023
    },
    {
        site_id: 10,
        site_name: "Bangka Island",
        country: "Indonesia",
        region: "Asia",
        category: "mineral_extraction",
        subcategory: "tin",
        latitude: -2.0,
        longitude: 106.0,
        production_volume: 80000,
        production_unit: "MT_annual",
        workforce_size: 150000,
        avg_wage_usd_monthly: 300,
        environmental_impact_score: 9,
        human_rights_violations: "marine_ecosystem_destruction",
        key_companies: "PT Timah, illegal miners",
        source_authors: "Geographical",
        data_year: 2023
    },
    {
        site_id: 11,
        site_name: "Bangalore",
        country: "India",
        region: "Asia",
        category: "digital_labor",
        subcategory: "data_annotation",
        latitude: 12.97,
        longitude: 77.6,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 250000,
        avg_wage_usd_monthly: 350,
        environmental_impact_score: 1,
        human_rights_violations: "platform_exploitation",
        key_companies: "Amazon, iMerit, Clickworker",
        source_authors: "Gray & Suri, Fairwork",
        data_year: 2024
    },
    {
        site_id: 12,
        site_name: "Manila",
        country: "Philippines",
        region: "Asia",
        category: "digital_labor",
        subcategory: "data_annotation",
        latitude: 14.6,
        longitude: 121.0,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 150000,
        avg_wage_usd_monthly: 200,
        environmental_impact_score: 2,
        human_rights_violations: "wage_theft",
        key_companies: "Scale AI, Remotasks",
        source_authors: "Washington Post, Rest of World",
        data_year: 2024
    },
    {
        site_id: 13,
        site_name: "Nairobi",
        country: "Kenya",
        region: "Africa",
        category: "digital_labor",
        subcategory: "content_moderation",
        latitude: -1.29,
        longitude: 36.82,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 40000,
        avg_wage_usd_monthly: 65,
        environmental_impact_score: 3,
        human_rights_violations: "mental_health_trauma",
        key_companies: "Sama, Meta subcontractors",
        source_authors: "CBS News, 60 Minutes",
        data_year: 2024
    },
    {
        site_id: 14,
        site_name: "Caracas",
        country: "Venezuela",
        region: "South America",
        category: "digital_labor",
        subcategory: "platform_work",
        latitude: 10.5,
        longitude: -66.9,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 80000,
        avg_wage_usd_monthly: 180,
        environmental_impact_score: 4,
        human_rights_violations: "economic_desperation",
        key_companies: "Multiple platforms",
        source_authors: "Rest of World, Posada",
        data_year: 2024
    },
    {
        site_id: 15,
        site_name: "São Paulo",
        country: "Brazil",
        region: "South America",
        category: "digital_labor",
        subcategory: "BPO",
        latitude: -23.5,
        longitude: -46.6,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 133000,
        avg_wage_usd_monthly: 863,
        environmental_impact_score: 2,
        human_rights_violations: "precarious_employment",
        key_companies: "Multiple BPO companies",
        source_authors: "HatchWorks, TDS Global",
        data_year: 2024
    },
    {
        site_id: 16,
        site_name: "Cape Town",
        country: "South Africa",
        region: "Africa",
        category: "digital_labor",
        subcategory: "BPO",
        latitude: -33.9,
        longitude: 18.4,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 75000,
        avg_wage_usd_monthly: 800,
        environmental_impact_score: 2,
        human_rights_violations: "labor_arbitrage",
        key_companies: "Multiple BPO companies",
        source_authors: "BPESA",
        data_year: 2024
    },
    {
        site_id: 17,
        site_name: "Silicon Valley",
        country: "United States",
        region: "North America",
        category: "ai_research",
        subcategory: "development",
        latitude: 37.4,
        longitude: -122.1,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 500000,
        avg_wage_usd_monthly: 18000,
        environmental_impact_score: 1,
        human_rights_violations: "concentration_of_power",
        key_companies: "Google, Meta, OpenAI",
        source_authors: "Stanford HAI",
        data_year: 2024
    },
    {
        site_id: 18,
        site_name: "Boston",
        country: "United States",
        region: "North America",
        category: "ai_research",
        subcategory: "development",
        latitude: 42.4,
        longitude: -71.1,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 100000,
        avg_wage_usd_monthly: 16000,
        environmental_impact_score: 1,
        human_rights_violations: "research_concentration",
        key_companies: "MIT, Harvard",
        source_authors: "Federal Budget IQ",
        data_year: 2024
    },
    {
        site_id: 19,
        site_name: "Tel Aviv",
        country: "Israel",
        region: "Middle East",
        category: "ai_research",
        subcategory: "development",
        latitude: 32.1,
        longitude: 34.8,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 25000,
        avg_wage_usd_monthly: 12000,
        environmental_impact_score: 2,
        human_rights_violations: "innovation_hub",
        key_companies: "Multiple startups",
        source_authors: "Alicorn",
        data_year: 2024
    },
    {
        site_id: 20,
        site_name: "Toronto",
        country: "Canada",
        region: "North America",
        category: "ai_research",
        subcategory: "development",
        latitude: 43.7,
        longitude: -79.4,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 80000,
        avg_wage_usd_monthly: 14000,
        environmental_impact_score: 1,
        human_rights_violations: "tech_hub_growth",
        key_companies: "University of Toronto, Vector Institute",
        source_authors: "Alicorn",
        data_year: 2024
    },
    {
        site_id: 21,
        site_name: "Beijing",
        country: "China",
        region: "Asia",
        category: "ai_research",
        subcategory: "development",
        latitude: 39.9,
        longitude: 116.4,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 300000,
        avg_wage_usd_monthly: 8000,
        environmental_impact_score: 2,
        human_rights_violations: "state_controlled_development",
        key_companies: "Baidu, Alibaba, ByteDance",
        source_authors: "Visual Capitalist",
        data_year: 2024
    },
    {
        site_id: 22,
        site_name: "London",
        country: "United Kingdom",
        region: "Europe",
        category: "ai_research",
        subcategory: "development",
        latitude: 51.5,
        longitude: -0.1,
        production_volume: null,
        production_unit: "workers",
        workforce_size: 150000,
        avg_wage_usd_monthly: 15000,
        environmental_impact_score: 1,
        human_rights_violations: "financial_center_advantage",
        key_companies: "DeepMind, Multiple startups",
        source_authors: "Alicorn",
        data_year: 2024
    },
    {
        site_id: 23,
        site_name: "Northern Virginia",
        country: "United States",
        region: "North America",
        category: "data_centers",
        subcategory: "hyperscale",
        latitude: 38.9,
        longitude: -77.4,
        production_volume: 1799,
        production_unit: "MW_capacity",
        workforce_size: 25000,
        avg_wage_usd_monthly: 8000,
        environmental_impact_score: 7,
        human_rights_violations: "energy_consumption",
        key_companies: "Amazon, Microsoft, Google",
        source_authors: "IEA",
        data_year: 2024
    },
    {
        site_id: 24,
        site_name: "Dublin",
        country: "Ireland",
        region: "Europe",
        category: "data_centers",
        subcategory: "hyperscale",
        latitude: 53.3,
        longitude: -6.3,
        production_volume: 1200,
        production_unit: "MW_capacity",
        workforce_size: 15000,
        avg_wage_usd_monthly: 7000,
        environmental_impact_score: 8,
        human_rights_violations: "electricity_grid_strain",
        key_companies: "Google, Meta, Microsoft",
        source_authors: "IEA",
        data_year: 2024
    },
    {
        site_id: 25,
        site_name: "Singapore",
        country: "Singapore",
        region: "Asia",
        category: "data_centers",
        subcategory: "tropical",
        latitude: 1.35,
        longitude: 103.8,
        production_volume: 800,
        production_unit: "MW_capacity",
        workforce_size: 12000,
        avg_wage_usd_monthly: 6000,
        environmental_impact_score: 7,
        human_rights_violations: "water_consumption",
        key_companies: "Multiple operators",
        source_authors: "IEA",
        data_year: 2024
    },
    {
        site_id: 26,
        site_name: "Frankfurt",
        country: "Germany",
        region: "Europe",
        category: "data_centers",
        subcategory: "regional",
        latitude: 50.1,
        longitude: 8.7,
        production_volume: 600,
        production_unit: "MW_capacity",
        workforce_size: 8000,
        avg_wage_usd_monthly: 6500,
        environmental_impact_score: 6,
        human_rights_violations: "renewable_energy_transition",
        key_companies: "Multiple operators",
        source_authors: "IEA",
        data_year: 2024
    },
    {
        site_id: 27,
        site_name: "Shanghai",
        country: "China",
        region: "Asia",
        category: "data_centers",
        subcategory: "regional",
        latitude: 31.2,
        longitude: 121.5,
        production_volume: 900,
        production_unit: "MW_capacity",
        workforce_size: 20000,
        avg_wage_usd_monthly: 4000,
        environmental_impact_score: 6,
        human_rights_violations: "rapid_expansion",
        key_companies: "Alibaba, Tencent",
        source_authors: "Visual Capitalist",
        data_year: 2024
    },
    {
        site_id: 28,
        site_name: "Eemshaven",
        country: "Netherlands",
        region: "Europe",
        category: "data_centers",
        subcategory: "hyperscale",
        latitude: 53.4,
        longitude: 6.8,
        production_volume: 120,
        production_unit: "MW_single_facility",
        workforce_size: 500,
        avg_wage_usd_monthly: 7000,
        environmental_impact_score: 6,
        human_rights_violations: "renewable_powered",
        key_companies: "Google",
        source_authors: "IEA",
        data_year: 2024
    },
    // Additional sites continue with the same structure...
    // Including all the remaining sites from the original data
    {
        site_id: 34,
        site_name: "Sorowako Mine",
        country: "Indonesia",
        region: "Asia",
        category: "mineral_extraction",
        subcategory: "nickel",
        latitude: -2.5736,
        longitude: 121.3742,
        production_volume: 64100,
        production_unit: "MT_annual",
        workforce_size: 4000,
        avg_wage_usd_monthly: 1100,
        environmental_impact_score: 7,
        human_rights_violations: "land_disputes_criminalization_of_protest",
        key_companies: "PT Vale Indonesia, MIND ID, Vale Canada, Sumitomo Metal Mining",
        source_authors: "Discovery Alert, Wikipedia, Vale, BHRRC",
        data_year: 2024
    },
    {
        site_id: 35,
        site_name: "Rio Tuba Mine",
        country: "Philippines",
        region: "Asia",
        category: "mineral_extraction",
        subcategory: "nickel",
        latitude: 8.57,
        longitude: 117.4189,
        production_volume: 46780,
        production_unit: "MT_annual",
        workforce_size: 2000,
        avg_wage_usd_monthly: 530,
        environmental_impact_score: 9,
        human_rights_violations: "water_contamination_health_impacts_indigenous_rights_violations",
        key_companies: "Nickel Asia Corporation, Sumitomo Metal Mining",
        source_authors: "BHRRC, FoE Japan, Global Witness, Wikipedia",
        data_year: 2024
    },
    {
        site_id: 36,
        site_name: "Kola MMC (Norilsk Nickel)",
        country: "Russia",
        region: "Europe",
        category: "mineral_extraction",
        subcategory: "nickel",
        latitude: 69.3333,
        longitude: 88.2167,
        production_volume: 205000,
        production_unit: "MT_annual_company_total",
        workforce_size: 7000,
        avg_wage_usd_monthly: 2250,
        environmental_impact_score: 10,
        human_rights_violations: "extreme_air_pollution_right_to_healthy_environment",
        key_companies: "MMC Norilsk Nickel (Nornickel)",
        source_authors: "Bellona.org, Nornickel, GlobalData",
        data_year: 2024
    },
    // Additional mining and data center sites...
    {
        site_id: 49,
        site_name: "Santiago Data Center Hub",
        country: "Chile",
        region: "South America",
        category: "data_centers",
        subcategory: "regional",
        latitude: -33.45,
        longitude: -70.67,
        production_volume: 338,
        production_unit: "MW_capacity",
        workforce_size: 2750,
        avg_wage_usd_monthly: 2200,
        environmental_impact_score: 7,
        human_rights_violations: "water_usage_concerns",
        key_companies: "Google, Microsoft, AWS, Equinix",
        source_authors: "Rest of World, Business & Human Rights",
        data_year: 2024
    }
];

// Global South countries classification
const globalSouthCountries = [
    'Democratic Republic of Congo', 'Bolivia', 'Chile', 'Myanmar', 'Indonesia',
    'India', 'Philippines', 'Kenya', 'Venezuela', 'Brazil', 'South Africa',
    'Argentina', 'Peru', 'Madagascar', 'Papua New Guinea', 'Guinea'
];

// Color scheme matching the original visualization
const colorScheme = {
    'mineral_extraction': '#d32f2f',    // Deep red - extraction/exploitation
    'digital_labor': '#1976d2',        // Blue - labor/workers
    'ai_research': '#388e3c',          // Green - research/development
    'data_centers': '#f57c00',         // Orange - infrastructure
    'environmental_impact': '#795548'   // Brown - environmental
};

// Flow definitions for arrows (matching the original Jupyter notebook flows)
const flowDefinitions = {
    // Primary mineral extraction flows
    resource_flows: [
        // DRC Cobalt → Silicon Valley
        { start: [25.5, -10.7], end: [-122.1, 37.4], weight: 3, label: 'Cobalt' },
        // Lithium Triangle → Silicon Valley  
        { start: [-67.49, -20.13], end: [-122.1, 37.4], weight: 3, label: 'Lithium' },
        // Chilean Copper → Boston
        { start: [-69.1, -24.3], end: [-71.1, 42.4], weight: 2, label: 'Copper' },
        // Indonesian Nickel → Beijing
        { start: [121.3742, -2.5736], end: [116.4, 39.9], weight: 2, label: 'Nickel' },
        // Philippines Nickel → Silicon Valley
        { start: [117.4189, 8.57], end: [-122.1, 37.4], weight: 2, label: 'Nickel' },
        // Russian Nickel → London
        { start: [88.2167, 69.3333], end: [-0.1, 51.5], weight: 2, label: 'Nickel' },
        // Bayan Obo Rare Earth → Beijing
        { start: [109.9, 41.8], end: [116.4, 39.9], weight: 5, label: 'Rare Earth Hub' },
        // Bayan Obo → Silicon Valley
        { start: [109.9, 41.8], end: [-122.1, 37.4], weight: 5, label: 'Rare Earth Hub' },
        // Bayan Obo → London
        { start: [109.9, 41.8], end: [-0.1, 51.5], weight: 5, label: 'Rare Earth Hub' },
        // Myanmar Rare Earth → Beijing
        { start: [98.0, 25.0], end: [116.4, 39.9], weight: 3, label: 'Rare Earth' }
    ],
    
    // Digital labor flows
    labor_flows: [
        // Bangalore → Silicon Valley
        { start: [77.6, 12.97], end: [-122.1, 37.4], weight: 2, label: 'Data Annotation' },
        // Manila → Silicon Valley
        { start: [121.0, 14.6], end: [-122.1, 37.4], weight: 2, label: 'Content Moderation' },
        // Nairobi → London
        { start: [36.82, -1.29], end: [-0.1, 51.5], weight: 2, label: 'Content Moderation' },
        // São Paulo → Toronto
        { start: [-46.6, -23.5], end: [-79.4, 43.7], weight: 1, label: 'BPO Services' },
        // Cape Town → London
        { start: [18.4, -33.9], end: [-0.1, 51.5], weight: 1, label: 'BPO Services' },
        // Caracas → Silicon Valley
        { start: [-66.9, 10.5], end: [-122.1, 37.4], weight: 1, label: 'Platform Work' }
    ]
};

export { aiValueChainData, globalSouthCountries, colorScheme, flowDefinitions };